version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Map the container port 3000 to your local port 3000
    volumes:
      - .:/usr/src/app  # Mount the current directory to the app's working directory inside the container
    environment:
      - NODE_ENV=production  # Set the environment variable for production (you can adjust this)
    restart: always  # Restart the container automatically if it crashes or the system reboots
